using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheIsleAdminHelp.classe
{
    public class Stat
    {
        public int Herbi { get; set; }
        public int Carni { get; set; }

        //Carni

        public int Rex { get; set; }
        public int RexBB { get; set; }
        public int RexJuv { get; set; }
        public int RexSub { get; set; }
        public int RexAdult { get; set; }
        public int RexF { get; set; }
        public int RexBBF { get; set; }
        public int RexJuvF { get; set; }
        public int RexSubF { get; set; }
        public int RexAdultF { get; set; }
        public int RexM { get; set; }
        public int RexBBM { get; set; }
        public int RexJuvM { get; set; }
        public int RexSubM { get; set; }
        public int RexAdultM { get; set; }

        public int Allo { get; set; }
        public int AlloBB { get; set; }
        public int AlloJuv { get; set; }
        public int AlloSub { get; set; }
        public int AlloAdult { get; set; }
        public int AlloF { get; set; }
        public int AlloBBF { get; set; }
        public int AlloJuvF { get; set; }
        public int AlloSubF { get; set; }
        public int AlloAdultF { get; set; }
        public int AlloM { get; set; }
        public int AlloBBM { get; set; }
        public int AlloJuvM { get; set; }
        public int AlloSubM { get; set; }
        public int AlloAdultM { get; set; }

        public int Carno { get; set; }
        public int CarnoBB { get; set; }
        public int CarnoJuv { get; set; }
        public int CarnoSub { get; set; }
        public int CarnoAdult { get; set; }
        public int CarnoF { get; set; }
        public int CarnoBBF { get; set; }
        public int CarnoJuvF { get; set; }
        public int CarnoSubF { get; set; }
        public int CarnoAdultF { get; set; }
        public int CarnoM { get; set; }
        public int CarnoBBM { get; set; }
        public int CarnoJuvM { get; set; }
        public int CarnoSubM { get; set; }
        public int CarnoAdultM { get; set; }

        public int Cerato { get; set; }
        public int CeratoBB { get; set; }
        public int CeratoJuv { get; set; }
        public int CeratoSub { get; set; }
        public int CeratoAdult { get; set; }
        public int CeratoF { get; set; }
        public int CeratoBBF { get; set; }
        public int CeratoJuvF { get; set; }
        public int CeratoSubF { get; set; }
        public int CeratoAdultF { get; set; }
        public int CeratoM { get; set; }
        public int CeratoBBM { get; set; }
        public int CeratoJuvM { get; set; }
        public int CeratoSubM { get; set; }
        public int CeratoAdultM { get; set; }

        public int Dilo { get; set; }
        public int DiloBB { get; set; }
        public int DiloJuv { get; set; }
        public int DiloSub { get; set; }
        public int DiloAdult { get; set; }
        public int DiloF { get; set; }
        public int DiloBBF { get; set; }
        public int DiloJuvF { get; set; }
        public int DiloSubF { get; set; }
        public int DiloAdultF { get; set; }
        public int DiloM { get; set; }
        public int DiloBBM { get; set; }
        public int DiloJuvM { get; set; }
        public int DiloSubM { get; set; }
        public int DiloAdultM { get; set; }

        public int Giga { get; set; }
        public int GigaBB { get; set; }
        public int GigaJuv { get; set; }
        public int GigaSub { get; set; }
        public int GigaAdult { get; set; }
        public int GigaF { get; set; }
        public int GigaBBF { get; set; }
        public int GigaJuvF { get; set; }
        public int GigaSubF { get; set; }
        public int GigaAdultF { get; set; }
        public int GigaM { get; set; }
        public int GigaBBM { get; set; }
        public int GigaJuvM { get; set; }
        public int GigaSubM { get; set; }
        public int GigaAdultM { get; set; }

        public int Utah { get; set; }
        public int UtahBB { get; set; }
        public int UtahJuv { get; set; }
        public int UtahSub { get; set; }
        public int UtahAdult { get; set; }
        public int UtahF { get; set; }
        public int UtahBBF { get; set; }
        public int UtahJuvF { get; set; }
        public int UtahSubF { get; set; }
        public int UtahAdultF { get; set; }
        public int UtahM { get; set; }
        public int UtahBBM { get; set; }
        public int UtahJuvM { get; set; }
        public int UtahSubM { get; set; }
        public int UtahAdultM { get; set; }

        public int Acro { get; set; }
        public int AcroBB { get; set; }
        public int AcroJuv { get; set; }
        public int AcroSub { get; set; }
        public int AcroAdult { get; set; }
        public int AcroF { get; set; }
        public int AcroBBF { get; set; }
        public int AcroJuvF { get; set; }
        public int AcroSubF { get; set; }
        public int AcroAdultF { get; set; }
        public int AcroM { get; set; }
        public int AcroBBM { get; set; }
        public int AcroJuvM { get; set; }
        public int AcroSubM { get; set; }
        public int AcroAdultM { get; set; }

        public int Spino { get; set; }
        public int SpinoBB { get; set; }
        public int SpinoJuv { get; set; }
        public int SpinoSub { get; set; }
        public int SpinoAdult { get; set; }
        public int SpinoF { get; set; }
        public int SpinoBBF { get; set; }
        public int SpinoJuvF { get; set; }
        public int SpinoSubF { get; set; }
        public int SpinoAdultF { get; set; }
        public int SpinoM { get; set; }
        public int SpinoBBM { get; set; }
        public int SpinoJuvM { get; set; }
        public int SpinoSubM { get; set; }
        public int SpinoAdultM { get; set; }

        public int Velociraptor { get; set; }
        public int VelociraptorBB { get; set; }
        public int VelociraptorJuv { get; set; }
        public int VelociraptorSub { get; set; }
        public int VelociraptorAdult { get; set; }
        public int VelociraptorF { get; set; }
        public int VelociraptorBBF { get; set; }
        public int VelociraptorJuvF { get; set; }
        public int VelociraptorSubF { get; set; }
        public int VelociraptorAdultF { get; set; }
        public int VelociraptorM { get; set; }
        public int VelociraptorBBM { get; set; }
        public int VelociraptorJuvM { get; set; }
        public int VelociraptorSubM { get; set; }
        public int VelociraptorAdultM { get; set; }

        public int Sucho { get; set; }
        public int SuchoBB { get; set; }
        public int SuchoJuv { get; set; }
        public int SuchoSub { get; set; }
        public int SuchoAdult { get; set; }
        public int SuchoF { get; set; }
        public int SuchoBBF { get; set; }
        public int SuchoJuvF { get; set; }
        public int SuchoSubF { get; set; }
        public int SuchoAdultF { get; set; }
        public int SuchoM { get; set; }
        public int SuchoBBM { get; set; }
        public int SuchoJuvM { get; set; }
        public int SuchoSubM { get; set; }
        public int SuchoAdultM { get; set; }

        public int Herrera { get; set; }
        public int HerreraBB { get; set; }
        public int HerreraJuv { get; set; }
        public int HerreraSub { get; set; }
        public int HerreraAdult { get; set; }
        public int HerreraF { get; set; }
        public int HerreraBBF { get; set; }
        public int HerreraJuvF { get; set; }
        public int HerreraSubF { get; set; }
        public int HerreraAdultF { get; set; }
        public int HerreraM { get; set; }
        public int HerreraBBM { get; set; }
        public int HerreraJuvM { get; set; }
        public int HerreraSubM { get; set; }
        public int HerreraAdultM { get; set; }

        public int Bary { get; set; }
        public int BaryBB { get; set; }
        public int BaryJuv { get; set; }
        public int BarySub { get; set; }
        public int BaryAdult { get; set; }
        public int BaryF { get; set; }
        public int BaryBBF { get; set; }
        public int BaryJuvF { get; set; }
        public int BarySubF { get; set; }
        public int BaryAdultF { get; set; }
        public int BaryM { get; set; }
        public int BaryBBM { get; set; }
        public int BaryJuvM { get; set; }
        public int BarySubM { get; set; }
        public int BaryAdultM { get; set; }

        public int Austro { get; set; }
        public int AustroBB { get; set; }
        public int AustroJuv { get; set; }
        public int AustroSub { get; set; }
        public int AustroAdult { get; set; }
        public int AustroF { get; set; }
        public int AustroBBF { get; set; }
        public int AustroJuvF { get; set; }
        public int AustroSubF { get; set; }
        public int AustroAdultF { get; set; }
        public int AustroM { get; set; }
        public int AustroBBM { get; set; }
        public int AustroJuvM { get; set; }
        public int AustroSubM { get; set; }
        public int AustroAdultM { get; set; }

        public int Albert { get; set; }
        public int AlbertBB { get; set; }
        public int AlbertJuv { get; set; }
        public int AlbertSub { get; set; }
        public int AlbertAdult { get; set; }
        public int AlbertF { get; set; }
        public int AlbertBBF { get; set; }
        public int AlbertJuvF { get; set; }
        public int AlbertSubF { get; set; }
        public int AlbertAdultF { get; set; }
        public int AlbertM { get; set; }
        public int AlbertBBM { get; set; }
        public int AlbertJuvM { get; set; }
        public int AlbertSubM { get; set; }
        public int AlbertAdultM { get; set; }

        // Herbi

        public int Diablo { get; set; }
        public int DiabloBB { get; set; }
        public int DiabloJuv { get; set; }
        public int DiabloSub { get; set; }
        public int DiabloAdult { get; set; }
        public int DiabloF { get; set; }
        public int DiabloBBF { get; set; }
        public int DiabloJuvF { get; set; }
        public int DiabloSubF { get; set; }
        public int DiabloAdultF { get; set; }
        public int DiabloM { get; set; }
        public int DiabloBBM { get; set; }
        public int DiabloJuvM { get; set; }
        public int DiabloSubM { get; set; }
        public int DiabloAdultM { get; set; }

        public int Dryo { get; set; }
        public int DryoBB { get; set; }
        public int DryoJuv { get; set; }
        public int DryoSub { get; set; }
        public int DryoAdult { get; set; }
        public int DryoF { get; set; }
        public int DryoBBF { get; set; }
        public int DryoJuvF { get; set; }
        public int DryoSubF { get; set; }
        public int DryoAdultF { get; set; }
        public int DryoM { get; set; }
        public int DryoBBM { get; set; }
        public int DryoJuvM { get; set; }
        public int DryoSubM { get; set; }
        public int DryoAdultM { get; set; }

        public int Galli { get; set; }
        public int GalliBB { get; set; }
        public int GalliJuv { get; set; }
        public int GalliSub { get; set; }
        public int GalliAdult { get; set; }
        public int GalliF { get; set; }
        public int GalliBBF { get; set; }
        public int GalliJuvF { get; set; }
        public int GalliSubF { get; set; }
        public int GalliAdultF { get; set; }
        public int GalliM { get; set; }
        public int GalliBBM { get; set; }
        public int GalliJuvM { get; set; }
        public int GalliSubM { get; set; }
        public int GalliAdultM { get; set; }

        public int Maia { get; set; }
        public int MaiaBB { get; set; }
        public int MaiaJuv { get; set; }
        public int MaiaSub { get; set; }
        public int MaiaAdult { get; set; }
        public int MaiaF { get; set; }
        public int MaiaBBF { get; set; }
        public int MaiaJuvF { get; set; }
        public int MaiaSubF { get; set; }
        public int MaiaAdultF { get; set; }
        public int MaiaM { get; set; }
        public int MaiaBBM { get; set; }
        public int MaiaJuvM { get; set; }
        public int MaiaSubM { get; set; }
        public int MaiaAdultM { get; set; }

        public int Para { get; set; }
        public int ParaBB { get; set; }
        public int ParaJuv { get; set; }
        public int ParaSub { get; set; }
        public int ParaAdult { get; set; }
        public int ParaF { get; set; }
        public int ParaBBF { get; set; }
        public int ParaJuvF { get; set; }
        public int ParaSubF { get; set; }
        public int ParaAdultF { get; set; }
        public int ParaM { get; set; }
        public int ParaBBM { get; set; }
        public int ParaJuvM { get; set; }
        public int ParaSubM { get; set; }
        public int ParaAdultM { get; set; }

        public int Trike { get; set; }
        public int TrikeBB { get; set; }
        public int TrikeJuv { get; set; }
        public int TrikeSub { get; set; }
        public int TrikeAdult { get; set; }
        public int TrikeF { get; set; }
        public int TrikeBBF { get; set; }
        public int TrikeJuvF { get; set; }
        public int TrikeSubF { get; set; }
        public int TrikeAdultF { get; set; }
        public int TrikeM { get; set; }
        public int TrikeBBM { get; set; }
        public int TrikeJuvM { get; set; }
        public int TrikeSubM { get; set; }
        public int TrikeAdultM { get; set; }

        public int Pachy { get; set; }
        public int PachyBB { get; set; }
        public int PachyJuv { get; set; }
        public int PachySub { get; set; }
        public int PachyAdult { get; set; }
        public int PachyF { get; set; }
        public int PachyBBF { get; set; }
        public int PachyJuvF { get; set; }
        public int PachySubF { get; set; }
        public int PachyAdultF { get; set; }
        public int PachyM { get; set; }
        public int PachyBBM { get; set; }
        public int PachyJuvM { get; set; }
        public int PachySubM { get; set; }
        public int PachyAdultM { get; set; }

        public int Shan { get; set; }
        public int ShanBB { get; set; }
        public int ShanJuv { get; set; }
        public int ShanSub { get; set; }
        public int ShanAdult { get; set; }
        public int ShanF { get; set; }
        public int ShanBBF { get; set; }
        public int ShanJuvF { get; set; }
        public int ShanSubF { get; set; }
        public int ShanAdultF { get; set; }
        public int ShanM { get; set; }
        public int ShanBBM { get; set; }
        public int ShanJuvM { get; set; }
        public int ShanSubM { get; set; }
        public int ShanAdultM { get; set; }

        public int Camara { get; set; }
        public int CamaraBB { get; set; }
        public int CamaraJuv { get; set; }
        public int CamaraSub { get; set; }
        public int CamaraAdult { get; set; }
        public int CamaraF { get; set; }
        public int CamaraBBF { get; set; }
        public int CamaraJuvF { get; set; }
        public int CamaraSubF { get; set; }
        public int CamaraAdultF { get; set; }
        public int CamaraM { get; set; }
        public int CamaraBBM { get; set; }
        public int CamaraJuvM { get; set; }
        public int CamaraSubM { get; set; }
        public int CamaraAdultM { get; set; }

        public int Ava { get; set; }
        public int AvaBB { get; set; }
        public int AvaJuv { get; set; }
        public int AvaSub { get; set; }
        public int AvaAdult { get; set; }
        public int AvaF { get; set; }
        public int AvaBBF { get; set; }
        public int AvaJuvF { get; set; }
        public int AvaSubF { get; set; }
        public int AvaAdultF { get; set; }
        public int AvaM { get; set; }
        public int AvaBBM { get; set; }
        public int AvaJuvM { get; set; }
        public int AvaSubM { get; set; }
        public int AvaAdultM { get; set; }

        public int Anky { get; set; }
        public int AnkyBB { get; set; }
        public int AnkyJuv { get; set; }
        public int AnkySub { get; set; }
        public int AnkyAdult { get; set; }
        public int AnkyF { get; set; }
        public int AnkyBBF { get; set; }
        public int AnkyJuvF { get; set; }
        public int AnkySubF { get; set; }
        public int AnkyAdultF { get; set; }
        public int AnkyM { get; set; }
        public int AnkyBBM { get; set; }
        public int AnkyJuvM { get; set; }
        public int AnkySubM { get; set; }
        public int AnkyAdultM { get; set; }

        public int Oro { get; set; }
        public int OroBB { get; set; }
        public int OroJuv { get; set; }
        public int OroSub { get; set; }
        public int OroAdult { get; set; }
        public int OroF { get; set; }
        public int OroBBF { get; set; }
        public int OroJuvF { get; set; }
        public int OroSubF { get; set; }
        public int OroAdultF { get; set; }
        public int OroM { get; set; }
        public int OroBBM { get; set; }
        public int OroJuvM { get; set; }
        public int OroSubM { get; set; }
        public int OroAdultM { get; set; }

        public int Psittaco { get; set; }
        public int PsittacoBB { get; set; }
        public int PsittacoJuv { get; set; }
        public int PsittacoSub { get; set; }
        public int PsittacoAdult { get; set; }
        public int PsittacoF { get; set; }
        public int PsittacoBBF { get; set; }
        public int PsittacoJuvF { get; set; }
        public int PsittacoSubF { get; set; }
        public int PsittacoAdultF { get; set; }
        public int PsittacoM { get; set; }
        public int PsittacoBBM { get; set; }
        public int PsittacoJuvM { get; set; }
        public int PsittacoSubM { get; set; }
        public int PsittacoAdultM { get; set; }

        public int Puerta { get; set; }
        public int PuertaBB { get; set; }
        public int PuertaJuv { get; set; }
        public int PuertaSub { get; set; }
        public int PuertaAdult { get; set; }
        public int PuertaF { get; set; }
        public int PuertaBBF { get; set; }
        public int PuertaJuvF { get; set; }
        public int PuertaSubF { get; set; }
        public int PuertaAdultF { get; set; }
        public int PuertaM { get; set; }
        public int PuertaBBM { get; set; }
        public int PuertaJuvM { get; set; }
        public int PuertaSubM { get; set; }
        public int PuertaAdultM { get; set; }

        public int Stego { get; set; }
        public int StegoBB { get; set; }
        public int StegoJuv { get; set; }
        public int StegoSub { get; set; }
        public int StegoAdult { get; set; }
        public int StegoF { get; set; }
        public int StegoBBF { get; set; }
        public int StegoJuvF { get; set; }
        public int StegoSubF { get; set; }
        public int StegoAdultF { get; set; }
        public int StegoM { get; set; }
        public int StegoBBM { get; set; }
        public int StegoJuvM { get; set; }
        public int StegoSubM { get; set; }
        public int StegoAdultM { get; set; }

        public int Therizino { get; set; }
        public int TherizinoBB { get; set; }
        public int TherizinoJuv { get; set; }
        public int TherizinoSub { get; set; }
        public int TherizinoAdult { get; set; }
        public int TherizinoF { get; set; }
        public int TherizinoBBF { get; set; }
        public int TherizinoJuvF { get; set; }
        public int TherizinoSubF { get; set; }
        public int TherizinoAdultF { get; set; }
        public int TherizinoM { get; set; }
        public int TherizinoBBM { get; set; }
        public int TherizinoJuvM { get; set; }
        public int TherizinoSubM { get; set; }
        public int TherizinoAdultM { get; set; }

        public int Autre { get; set; }
        public int AutreBB { get; set; }
        public int AutreJuv { get; set; }
        public int AutreSub { get; set; }
        public int AutreAdult { get; set; }
        public int AutreF { get; set; }
        public int AutreBBF { get; set; }
        public int AutreJuvF { get; set; }
        public int AutreSubF { get; set; }
        public int AutreAdultF { get; set; }
        public int AutreM { get; set; }
        public int AutreBBM { get; set; }
        public int AutreJuvM { get; set; }
        public int AutreSubM { get; set; }
        public int AutreAdultM { get; set; }
    }
}
